name: timefed
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - h5py
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - pytables
  - tsfresh
  - tqdm
  - tables
  - scikit-learn
  - seaborn
  - scipy
  - xarray
  - pip
  - pip:
    - mlky
    - ray
    # - mat4py>=0.4.3
    # - mat73>=0.46
    # - pvlib>=0.8.1
    # - pyyaml>=5.4.1
