#
preprocess:
  input:
    file: /Users/jamesmo/projects/mloc/local/data/v2/data.h5
    key: merged
  subselect:
    gte: 2018/05/03
    lt: 2020/12/30
  train:
    lte: 2019/12/31
  test:
    gt: 2019/12/31
  exclude: [r0_day, r0_night, Cn2, wind_direction, month]
  output:
    file: /Users/jamesmo/projects/mloc/local/data/v2/r0.preprocess.h5
    key: default
#
classify:
  input:
    file: /Users/jamesmo/projects/mloc/local/data/v2/r0.preprocess.h5
    key: default
  label: r0
  dropna: True
  plots:
    enabled: True
    directory: /Users/jamesmo/projects/mloc/local/plots/classify
    errors_in_time:
    scatter_with_errors:
      x:
        min: 0
        max: 20
      y:
        min: 0
        max: 20
      step_length: !!python/complex 100j
      samples: 1000
      size: 25
      alpha: .4
      figsize: [10, 10]
      file: scatter_errors.png
    importances:
      figsize: [20, 10]
      labelrotation: 30
      title: Feature Importances
      file: feature_importances.png
    histogram_errors:
      min: 0
      max: 80
      bins: 81
      figsize: [20, 10]
      file: histogram_errors.png
    local_synchrony:
      feature1: r0
      feature2: logCn2
      window_size: 120
      figsize: [30, 6]
      file: local_synchony.png
  features:
    select:
    exclude: [r0_day, r0_night, Cn2, o(I)_I, wind_direction, month]
#
extract_features:
  window: 5 day
  step: 1
  observations: 5
  cores: 8g
  input:
    file: /Users/jamesmo/projects/mloc/local/data/v2/r0.preprocess.h5
    key: default/full
  output:
    file: /Users/jamesmo/projects/mloc/local/data/v2/r0.features.h5
    key: default
  prompt:
    features: False
  features:
    whitelist:
    blacklist:
