#
preprocess:
  input:
    file: /Users/jamesmo/projects/mloc/local/data/v2/data.h5
    key: merged
  subselect:
    gte: 2018/05/03
    lt: 2020/12/30
  train:
    lte: 2019/12/31
  test:
    gt: 2019/12/31
  exclude: [r0_day, r0_night, Cn2, wind_direction, month]
  features: []
  shift: [r0]
  output:
    file: /Users/jamesmo/projects/mloc/local/data/v2/r0.preprocess.h5
    key: default
#
classify:
  input:
    file: /Users/jamesmo/projects/mloc/local/data/v2/r0.preprocess.h5
    train: default/train
    test: default/test
  label: r0
  dropna: True
  features:
    select:
    exclude: [r0_day, r0_night, Cn2, o(I)_I, wind_direction, month]
  plots:
    enabled: True
    directory: /Users/jamesmo/projects/mloc/local/plots/classify/r0
    errors_in_time:
    scatter_with_errors:
      x:
        min: 0
        max: 20
      y:
        min: 0
        max: 20
      step_length: !!python/complex 100j
      samples: 1000
      size: 25
      alpha: .4
      figsize: [10, 10]
      file: scatter_errors.png
    importances:
      figsize: [20, 10]
      labelrotation: 30
      number:
      title: Feature Importances
      file: feature_importances.png
    histogram_errors:
      min: 0
      max: 80
      bins: 81
      figsize: [20, 10]
      file: histogram_errors.png
    local_synchrony:
      feature1: r0
      feature2: logCn2
      window_size: 120
      figsize: [30, 6]
      file: local_synchony.png
    date_range:
      figsize: [20, 10]
      file: date_range.png
      dates:
        5-30-20:
          start: 2020/05/30 00:00
          end  : 2020/05/31 00:00
        8-30-20:
          start: 2020/08/29 00:00
          end  : 2020/08/30 00:00
        2-15-20:
          start: 2020/02/15 00:00
          end  : 2020/02/16 00:00
        11-15-20:
          start: 2020/11/15 00:00
          end  : 2020/11/16 00:00
#
extract_features:
  window: 5 days
  step: 1000
  observations: 5
  cores: 8
  input:
    file: /Users/jamesmo/projects/mloc/local/data/v2/r0.preprocess.h5
    key: default/full
  output:
    file: /Users/jamesmo/projects/mloc/local/data/v2/r0.features.h5
    key: default
  prompt:
    features: False
  features:
    whitelist:
    blacklist:
