# Preprocess raw data
preprocess:
  input:
    file: /data1/mloc/local/data/v3/data.h5
    key: merged
  subselect:
    gte: 2018/05/03
    lt: 2020/12/30
  train:
    lte: 2019/12/31
  test:
    gt: 2019/12/31
  exclude: [r0, r0_day, r0_night, r0_day_10T, r0_night_10T, wind_direction, o(I)_I, Cn2, Cn2_10T]
  features:
    calc: [day]
    log: [Cn2_10T]
  shift: []
  output:
    file: /data1/mloc/local/data/v3/r0_features.5mins.5ptwin.OC.h5
    key: preprocess

# Extract tsfresh features from windows
extract_features:
  window: 25 min
  step: 1
  observations: 5
  cores: 64
  label: r0_10T
  input:
    file: /data1/mloc/local/data/v3/r0_features.5mins.5ptwin.OC.h5
    key: preprocess/full
  output:
    file: /data1/mloc/local/data/v3/r0_features.5mins.5ptwin.OC.h5
    key: features
  prompt:
    features: False
  features:
    whitelist:
    blacklist:
  drop: [r0_10T, day, solar_zenith_angle]

# Preprocess the extracted features
preprocess_features:
  input:
    file: /data1/mloc/local/data/v3/r0_features.5mins.5ptwin.OC.h5
    key: features/select
  subselect:
    gte: 2018/05/03
    lt: 2020/12/30
  train:
    lte: 2019/12/31
  test:
    gt: 2019/12/31
  exclude: []
  features:
    calc: []
    log: []
  shift: []
  output:
    file: /data1/mloc/local/data/v3/r0_features.5mins.5ptwin.OC.h5
    key: features/preprocess

# Train and test a model
classify:
  input:
    file: /data1/mloc/local/data/v3/r0_features.5mins.5ptwin.OC.h5
    train: features/preprocess/train
    test: features/preprocess/test
  label: r0_10T
  dropna: True
  plots:
    enabled: True
    directory: /data1/mloc/local/plots/r0_features.5mins.5ptwin.OC/
    units:
      r0_10T: cm
      datetime: UTC
    errors_in_time:
    scatter_with_errors:
      x:
        min: 0
        max: 20
      y:
        min: 0
        max: 20
      colorscale:
        min: 0
        max: .5
      step_length: !!python/complex 100j
      samples: 1000
      size: 25
      alpha: .4
      figsize: [10, 10]
      file: scatter_errors.png
    importances:
      figsize: [20, 30]
      number: 20
      labelrotation: 90
      title: Feature Importances
      file: feature_importances.png
    histogram_errors:
      min: 0
      max: 80
      bins: 81
      figsize: [20, 10]
      file: histogram_errors.png
    local_synchrony:
      feature1: r0_10T
      feature2: log_Cn2_10T
      window_size: 120
      figsize: [30, 6]
      file: local_synchony.png
    date_range:
      figsize: [20, 10]
      file: date_range.png
      dates:
        5-29-20:
          start: 2020/05/29 00:00
          end  : 2020/05/29 23:59
        8-29-20:
          start: 2020/08/30 00:00
          end  : 2020/08/30 23:59
        2-15-20:
          start: 2020/02/15 00:00
          end  : 2020/02/15 23:59
        11-15-20:
          start: 2020/11/15 00:00
          end  : 2020/11/15 23:59
        7-15-20:
          start: 2020/07/15 00:00
          end  : 2020/07/15 23:59
        8-04-20:
          start: 2020/08/04 00:00
          end  : 2020/08/04 23:59
        10-12-20:
          start: 2020/10/12 00:00
          end  : 2020/10/12 23:59
        12-25-20:
          start: 2020/12/25 00:00
          end  : 2020/12/25 23:59
  features:
    select:
    exclude:
#
