#
preprocess:
  input:
    file: /Users/jamesmo/projects/mloc/local/data/v2/data.h5
    key: merged
  subselect:
    gte: 2018/05/03
    lt: 2020/12/30
  train:
    lte: 2019/12/31
  test:
    gt: 2019/12/31
  exclude: [r0_day, r0_night, r0, Cn2, logCn2, o(I)_I, wind_direction, month]
  output:
    file: /Users/jamesmo/projects/mloc/local/data/v2/temperature.preprocess.h5
    key: base
#
classify:
  input:
    file: /Users/jamesmo/projects/mloc/local/data/v2/temperature.preprocess.h5
    train: base/train
    test: base/test
  label: temperature
  dropna: True
  plots:
    enabled: True
    directory: /Users/jamesmo/projects/mloc/local/plots/classify/temperature/
    errors_in_time:
    scatter_with_errors:
      x:
        min: -14
        max: 32
      y:
        min: -14
        max: 32
      step_length: !!python/complex 100j
      samples: 1000
      size: 25
      alpha: .4
      figsize: [10, 10]
      file: scatter_errors.png
    importances:
      figsize: [20, 10]
      labelrotation: 30
      number:
      title: Feature Importances
      file: feature_importances.png
    histogram_errors:
      min: 0
      max: 80
      bins: 81
      figsize: [20, 10]
      file: histogram_errors.png
    local_synchrony:
      feature1: temperature
      feature2: solar_zenith_angle
      window_size: 120
      figsize: [30, 6]
      file: local_synchony.png
  features:
    select:
    exclude: [r0_day, r0_night, Cn2, o(I)_I, month]
#
