# Preprocess raw data
preprocess:
  input:
    file: /data1/mloc/local/data/v3/data.h5
    key: merged
  subselect:
    gte: 2018/05/03
    lt: 2020/12/30
  train:
    lte: 2019/12/31
  test:
    gt: 2019/12/31
  exclude: [r0, r0_day, r0_night, r0_day_10T, r0_night_10T, o(I)_I, Cn2, Cn2_10T]
  features:
    calc: [day, minute]
    log: [Cn2_10T]
  shift:
    points: 36 # 12=1hour, 24=2, 36=3
    features: []
  output:
    file: /data1/mloc/local/runs/r0_features.5mins.all_historical/10ptwin.combined/data.h5
    key: preprocess

# Extract tsfresh features from windows
extract_features:
  window: 50 min
  step: 1
  observations: 10
  cores: 64
  label: r0_10T
  historical: [60, 120, 180] # in minutes
  train:
    lte: 2019/12/31
  test:
    gt: 2019/12/31
  input:
    file: /data1/mloc/local/runs/r0_features.5mins.all_historical/10ptwin.combined/data.h5
    key: preprocess/full
  output:
    file: /data1/mloc/local/runs/r0_features.5mins.all_historical/10ptwin.combined/data.h5
    key: features
  prompt:
    features: False
  features:
    whitelist:
    blacklist:
  drop: [r0_10T, solar_zenith_angle, day, minute]
  process: tsfresh

# Train and test a model
classify-1:
  input:
    file: /data1/mloc/local/runs/r0_features.5mins.all_historical/10ptwin.combined/data.h5
    train: features/60/train
    test: features/60/test
  label: r0_10T
  dropna: True
  plots:
    enabled: features
    directory: /data1/mloc/local/runs/r0_features.5mins.all_historical/10ptwin.combined/
    units:
      r0_10T: cm
      datetime: UTC
    errors_in_time:
    scatter_with_errors:
      x:
        min: 0
        max: 20
      y:
        min: 0
        max: 20
      colorscale:
        min: 0
        max: .5
      step_length: !!python/complex 100j
      samples: 1000
      size: 25
      alpha: .4
      figsize: [10, 10]
      file: scatter_errors.png
    importances:
      figsize: [20, 30]
      number: 20
      labelrotation: 90
      title: Feature Importances
      file: feature_importances.png
    histogram_errors:
      min: 0
      max: 80
      bins: 81
      figsize: [20, 10]
      file: histogram_errors.png
    local_synchrony:
      feature1: r0_10T
      feature2: r0_10T
      window_size: 120
      figsize: [30, 6]
      file: local_synchony.png
    date_range:
      figsize: [20, 10]
      file: date_range.png
      metrics: [rms]
      dates:
        5-25to29-20:
          start: 2020/05/25 00:00
          end  : 2020/05/29 23:59
        8-25to30-20:
          start: 2020/08/25 00:00
          end  : 2020/08/30 23:59
        2-15to20-20:
          start: 2020/02/15 00:00
          end  : 2020/02/20 23:59
        11-15to20-20:
          start: 2020/11/15 00:00
          end  : 2020/11/20 23:59
        7-10to15-20:
          start: 2020/07/10 00:00
          end  : 2020/07/15 23:59
        8-04to07-20:
          start: 2020/08/04 00:00
          end  : 2020/08/07 23:59
        10-12to15-20:
          start: 2020/10/12 00:00
          end  : 2020/10/15 23:59
        12-25to27-20:
          start: 2020/12/25 00:00
          end  : 2020/12/27 23:59
  features:
    select:
    exclude:
#
classify-2:
  input:
    file: /data1/mloc/local/runs/r0_features.5mins.all_historical/10ptwin.combined/data.h5
    train: features/120/train
    test: features/120/test
  label: r0_10T
  dropna: True
  plots:
    enabled: False
    directory: /data1/mloc/local/runs/r0_features.5mins.all_historical/10ptwin.combined/
    units:
      r0_10T: cm
      datetime: UTC
    errors_in_time:
    scatter_with_errors:
      x:
        min: 0
        max: 20
      y:
        min: 0
        max: 20
      colorscale:
        min: 0
        max: .5
      step_length: !!python/complex 100j
      samples: 1000
      size: 25
      alpha: .4
      figsize: [10, 10]
      file: scatter_errors.png
    importances:
      figsize: [20, 30]
      number: 20
      labelrotation: 90
      title: Feature Importances
      file: feature_importances.png
    histogram_errors:
      min: 0
      max: 80
      bins: 81
      figsize: [20, 10]
      file: histogram_errors.png
    local_synchrony:
      feature1: r0_10T
      feature2: r0_10T
      window_size: 120
      figsize: [30, 6]
      file: local_synchony.png
    date_range:
      figsize: [20, 10]
      file: date_range.png
      metrics: [rms]
      dates:
        5-25to29-20:
          start: 2020/05/25 00:00
          end  : 2020/05/29 23:59
        8-25to30-20:
          start: 2020/08/25 00:00
          end  : 2020/08/30 23:59
        2-15to20-20:
          start: 2020/02/15 00:00
          end  : 2020/02/20 23:59
        11-15to20-20:
          start: 2020/11/15 00:00
          end  : 2020/11/20 23:59
        7-10to15-20:
          start: 2020/07/10 00:00
          end  : 2020/07/15 23:59
        8-04to07-20:
          start: 2020/08/04 00:00
          end  : 2020/08/07 23:59
        10-12to15-20:
          start: 2020/10/12 00:00
          end  : 2020/10/15 23:59
        12-25to27-20:
          start: 2020/12/25 00:00
          end  : 2020/12/27 23:59
  features:
    select:
    exclude:

classify-3:
  input:
    file: /data1/mloc/local/runs/r0_features.5mins.all_historical/10ptwin.combined/data.h5
    train: features/180/train
    test: features/180/test
  label: r0_10T
  dropna: True
  plots:
    enabled: False
    directory: /data1/mloc/local/runs/r0_features.5mins.all_historical/10ptwin.combined/
    units:
      r0_10T: cm
      datetime: UTC
    errors_in_time:
    scatter_with_errors:
      x:
        min: 0
        max: 20
      y:
        min: 0
        max: 20
      colorscale:
        min: 0
        max: .5
      step_length: !!python/complex 100j
      samples: 1000
      size: 25
      alpha: .4
      figsize: [10, 10]
      file: scatter_errors.png
    importances:
      figsize: [20, 30]
      number: 20
      labelrotation: 90
      title: Feature Importances
      file: feature_importances.png
    histogram_errors:
      min: 0
      max: 80
      bins: 81
      figsize: [20, 10]
      file: histogram_errors.png
    local_synchrony:
      feature1: r0_10T
      feature2: r0_10T
      window_size: 120
      figsize: [30, 6]
      file: local_synchony.png
    date_range:
      figsize: [20, 10]
      file: date_range.png
      metrics: [rms]
      dates:
        5-25to29-20:
          start: 2020/05/25 00:00
          end  : 2020/05/29 23:59
        8-25to30-20:
          start: 2020/08/25 00:00
          end  : 2020/08/30 23:59
        2-15to20-20:
          start: 2020/02/15 00:00
          end  : 2020/02/20 23:59
        11-15to20-20:
          start: 2020/11/15 00:00
          end  : 2020/11/20 23:59
        7-10to15-20:
          start: 2020/07/10 00:00
          end  : 2020/07/15 23:59
        8-04to07-20:
          start: 2020/08/04 00:00
          end  : 2020/08/07 23:59
        10-12to15-20:
          start: 2020/10/12 00:00
          end  : 2020/10/15 23:59
        12-25to27-20:
          start: 2020/12/25 00:00
          end  : 2020/12/27 23:59
  features:
    select:
    exclude:
