# Preprocess raw data
preprocess:
  input:
    file: /data1/urebbapr/MLOC/local/data/v3/pwv.h5
    key: pwv
  subselect:
    gte: 2009/01/01
    lt: 2016/12/31
  train:
    lte: 2014/12/31
  test:
    gt: 2014/12/31
  exclude: [wind_direction, wind_gust]
  features:
    calc: [day, minute]
    log: []
  shift: # deprecated
    points: 12 # 12=1hour, 24=2, 36=3 
    features: [] 
  output:
    file: /data1/urebbapr/MLOC/local/runs/pwv/data.h5
    key: preprocess

# Extract tsfresh features from windows
extract_features:
  static: [day, minute, solar_zenith_angle]
  window: 300 min
  step: 1
  observations: 10
  cores: 64
  label: [water_vapor]
  historical: [30, 60, 90, 120, 150, 180]
  train:
    lte: 2014/12/31
  test:
    gt: 2014/12/31
  input:
    file: /data1/urebbapr/MLOC/local/runs/pwv/data.h5 
    key: preprocess/full
  output:
    file: /data1/urebbapr/MLOC/local/runs/pwv/data.h5
    key: features
  prompt:
    features: False
  features:
    whitelist:
    blacklist:
  drop: [day, minute, solar_zenith_angle]
  process: tsfresh

# Train and test a model
classify:
  input:
    file: /data1/urebbapr/MLOC/local/runs/pwv/data.h5
    key: features
    historical: [30, 60, 90, 120, 150, 180]
  output:
    models: /data1/urebbapr/MLOC/local/runs/pwv/temperature
    file: /data1/urebbapr/MLOC/local/runs/pwv/data.h5
    keys:
      scores: scores
      forecasts: forecasts
  label: water_vapor
  dropna: True
  plots:
    enabled: False
    directory: /data1/urebbapr/MLOC/local/runs/pwv
    units:
      temperature: C
      datetime: UTC
    errors_in_time:
    scatter_with_errors:
      x:
        min: 0 # CAN I LET THESE BE FREE?
        max: 20
      y:
        min: 0
        max: 20
      colorscale:
        min: 0
        max: .5
      step_length: !!python/complex 100j
      samples: 1000
      size: 25
      alpha: .4
      figsize: [10, 10]
      file: scatter_errors.png
    importances:
      figsize: [20, 30]
      number: 20
      labelrotation: 90
      title: Feature Importances
      file: feature_importances.png
    histogram_errors:
      min: 0
      max: 80
      bins: 81
      figsize: [20, 10]
      file: histogram_errors.png
    local_synchrony: # CAN I TURN OFF THIS PLOT?
      feature1: temperature
      feature2: temperature
      window_size: 120
      figsize: [30, 6]
      file: local_synchony.png
    date_range:
      figsize: [20, 10]
      file: date_range.png
      metrics: [rms]
      dates:
        5-25to29-20:
          start: 2020/05/25 00:00
          end  : 2020/05/29 23:59
        8-25to30-20:
          start: 2020/08/25 00:00
          end  : 2020/08/30 23:59
        2-15to20-20:
          start: 2020/02/15 00:00
          end  : 2020/02/20 23:59
        11-15to20-20:
          start: 2020/11/15 00:00
          end  : 2020/11/20 23:59
        7-10to15-20:
          start: 2020/07/10 00:00
          end  : 2020/07/15 23:59
        8-04to07-20:
          start: 2020/08/04 00:00
          end  : 2020/08/07 23:59
        10-12to15-20:
          start: 2020/10/12 00:00
          end  : 2020/10/15 23:59
        12-25to27-20:
          start: 2020/12/25 00:00
          end  : 2020/12/27 23:59
  features:
    select:
    exclude:
#
