extract_features-1:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/1/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/1
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-10:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/10/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/10
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-11:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/11/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/11
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-12:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/12/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/12
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-13:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/13/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/13
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-14:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/14/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/14
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-15:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/15/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/15
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-16:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/16/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/16
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-17:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/17/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/17
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-18:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/18/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/18
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-19:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/19/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/19
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-2:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/2/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/2
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-20:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/20/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/20
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-21:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/21/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/21
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-22:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/22/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/22
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-23:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/23/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/23
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-24:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/24/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/24
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-25:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/25/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/25
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-26:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/26/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/26
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-27:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/27/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/27
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-28:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/28/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/28
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-29:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/29/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/29
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-3:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/3/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/3
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-30:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/30/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/30
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-31:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/31/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/31
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-32:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/32/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/32
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-33:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/33/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/33
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-34:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/34/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/34
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-35:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/35/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/35
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-36:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/36/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/36
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-4:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/4/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/4
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-5:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/5/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/5
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-6:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/6/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/6
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-7:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/7/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/7
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-8:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/8/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/8
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-9:
  cores: 64
  drop:
  - pressure_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/pressure/9/full
  label: pressure
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/pressure/9
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
