extract_features-1:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/1
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-10:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/10
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-11:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/11
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-12:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/12
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-13:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/13
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-14:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/14
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-15:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/15
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-16:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/16
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-17:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/17
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-18:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/18
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-19:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/19
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-2:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/2
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-20:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/20
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-21:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/21
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-22:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/22
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-23:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/23
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-24:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/24
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-25:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/25
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-26:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/26
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-27:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/27
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-28:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/28
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-29:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/29
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-3:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/3
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-30:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/30
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-31:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/31
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-32:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/32
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-33:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/33
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-34:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/34
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-35:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/35
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-36:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/36
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-4:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/4
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-5:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/5
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-6:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/6
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-7:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/7
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-8:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/8
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-9:
  cores: 64
  drop:
  - r0_10T
  - solar_zenith_angle_shifted
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/9
  label: r0_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
