extract_features-1:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/1/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/1
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-10:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/10/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/10
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-11:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/11/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/11
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-12:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/12/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/12
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-13:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/13/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/13
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-14:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/14/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/14
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-15:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/15/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/15
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-16:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/16/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/16
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-17:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/17/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/17
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-18:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/18/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/18
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-19:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/19/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/19
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-2:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/2/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/2
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-20:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/20/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/20
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-21:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/21/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/21
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-22:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/22/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/22
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-23:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/23/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/23
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-24:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/24/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/24
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-25:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/25/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/25
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-26:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/26/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/26
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-27:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/27/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/27
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-28:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/28/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/28
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-29:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/29/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/29
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-3:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/3/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/3
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-30:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/30/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/30
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-31:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/31/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/31
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-32:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/32/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/32
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-33:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/33/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/33
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-34:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/34/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/34
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-35:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/35/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/35
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-36:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/36/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/36
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-4:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/4/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/4
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-5:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/5/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/5
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-6:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/6/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/6
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-7:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/7/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/7
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-8:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/8/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/8
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-9:
  cores: 64
  drop:
  - relative_humidity_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/relative_humidity/9/full
  label: relative_humidity
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/relative_humidity/9
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
