extract_features-1:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/1
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-10:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/10
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-11:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/11
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-12:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/12
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-13:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/13
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-14:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/14
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-15:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/15
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-16:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/16
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-17:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/17
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-18:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/18
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-19:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/19
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-2:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/2
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-20:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/20
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-21:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/21
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-22:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/22
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-23:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/23
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-24:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/24
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-25:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/25
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-26:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/26
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-27:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/27
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-28:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/28
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-29:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/29
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-3:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/3
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-30:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/30
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-31:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/31
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-32:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/32
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-33:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/33
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-34:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/34
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-35:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/35
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-36:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/36
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-4:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/4
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-5:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/5
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-6:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/6
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-7:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/7
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-8:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/8
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
extract_features-9:
  cores: 64
  drop:
  - log_Cn2_10T_shifted
  - solar_zenith_angle
  - day
  - minute
  features:
    blacklist: null
    whitelist: null
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: preprocess/log_Cn2_10T/9
  label: log_Cn2_10T
  observations: 10
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/data.h5
    key: features/log_Cn2_10T
  process: tsfresh
  prompt:
    features: false
  step: 1
  window: 50 min
