# Preprocess raw data
preprocess:
  input:
    file: /data1/mloc/local/data/v3/data.h5
    key: merged
  subselect:
    gte: 2018/05/03
    lt: 2020/12/30
  train:
    lte: 2019/12/31
  test:
    gt: 2019/12/31
  exclude: [r0, r0_day, r0_night, r0_day_10T, r0_night_10T, Cn2, Cn2_10T, wind_direction]
  features:
    calc: [day, minute, solar_zenith_angle]
    log: [Cn2_10T]
  shift:
    points: 12 # 12=1hour, 24=2, 36=3
    features: []
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/nonhist_r0_cn2_weather/data.h5
    key: preprocess

# Extract tsfresh features from windows
extract_features:
  window: 50 min
  step: 1
  observations: 10
  cores: 64
  label: [r0_10T]
  static: [solar_zenith_angle, day, minute]
  historical: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180] # in minutes
  train:
    lte: 2019/12/31
  test:
    gt: 2019/12/31
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/nonhist_r0_cn2_weather/data.h5
    key: preprocess/full
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/nonhist_r0_cn2_weather/data.h5
    key: features
  prompt:
    features: False
  features:
    whitelist:
    blacklist:
  drop: [solar_zenith_angle, day, minute, o(I)_I, r0_10T]
  process: tsfresh # median

# Train and test a model
classify:
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/nonhist_r0_cn2_weather/data.h5
    key: features/r0_10T/
    historical: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180]
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/nonhist_r0_cn2_weather/data.h5
    models: /data1/mloc/local/runs/3hr_forecast.5min_increment/nonhist_r0_cn2_weather/
    keys:
      scores: scores/r0_10T
      forecasts: forecasts/r0_10T
  label: r0_10T # temperature_H5
  dropna: True
  plots:
    enabled: False
  features:
    select:
    exclude:
