# Train and test a model
classify-5:
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/cn2_weather_data.h5
    key: features/log_Cn2_10T/
    historical: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180]
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/cn2_weather_data_data.h5
    models: /data1/mloc/local/runs/3hr_forecast.5min_increment/cn2_weather_data/
    keys:
      scores: scores/log_Cn2_10T
      forecasts: forecasts/log_Cn2_10T
  label: log_Cn2_10T # temperature_H5
  dropna: True
  plots:
    enabled: True
    directory: /data1/mloc/local/runs/3hr_forecast.5min_increment/cn2_weather_data/H5/
    units:
      log_Cn2_10T: ?
      datetime: UTC
    errors_in_time:
    scatter_with_errors:
      x:
        min: 0
        max: 20
      y:
        min: 0
        max: 20
      colorscale:
        min: 0
        max: .5
      step_length: !!python/complex 100j
      samples: 1000
      size: 25
      alpha: .4
      figsize: [10, 10]
      file: scatter_errors.png
    importances:
      figsize: [20, 30]
      number: 20
      labelrotation: 90
      title: Feature Importances
      file: feature_importances.png
    histogram_errors:
      min: 0
      max: 80
      bins: 81
      figsize: [20, 10]
      file: histogram_errors.png
    local_synchrony:
      feature1: pressure
      feature2: pressure
      window_size: 120
      figsize: [30, 6]
      file: local_synchony.png
    date_range:
      figsize: [20, 10]
      file: date_range.png
      metrics: [rms]
      dates:
        5-25to29-20:
          start: 2020/05/25 00:00
          end  : 2020/05/29 23:59
        8-25to30-20:
          start: 2020/08/25 00:00
          end  : 2020/08/30 23:59
        2-15to20-20:
          start: 2020/02/15 00:00
          end  : 2020/02/20 23:59
        11-15to20-20:
          start: 2020/11/15 00:00
          end  : 2020/11/20 23:59
        7-10to15-20:
          start: 2020/07/10 00:00
          end  : 2020/07/15 23:59
        8-04to07-20:
          start: 2020/08/04 00:00
          end  : 2020/08/07 23:59
        10-12to15-20:
          start: 2020/10/12 00:00
          end  : 2020/10/15 23:59
        12-25to27-20:
          start: 2020/12/25 00:00
          end  : 2020/12/27 23:59
  features:
    select:
    exclude:

classify-180:
  input:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/cn2_weather_data.h5
    key: features/log_Cn2_10T/
    historical: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180]
  output:
    file: /data1/mloc/local/runs/3hr_forecast.5min_increment/cn2_weather_data.h5
    models: /data1/mloc/local/runs/3hr_forecast.5min_increment/cn2_weather_data/
    keys:
      scores: scores/log_Cn2_10T
      forecasts: forecasts/log_Cn2_10T
  label: log_Cn2_10T # temperature_H5
  dropna: True
  plots:
    enabled: True
    directory: /data1/mloc/local/runs/3hr_forecast.5min_increment/cn2_weather_data/H180/
    units:
      log_Cn2_10T: ?
      datetime: UTC
    errors_in_time:
    scatter_with_errors:
      x:
        min: 0
        max: 20
      y:
        min: 0
        max: 20
      colorscale:
        min: 0
        max: .5
      step_length: !!python/complex 100j
      samples: 1000
      size: 25
      alpha: .4
      figsize: [10, 10]
      file: scatter_errors.png
    importances:
      figsize: [20, 30]
      number: 20
      labelrotation: 90
      title: Feature Importances
      file: feature_importances.png
    histogram_errors:
      min: 0
      max: 80
      bins: 81
      figsize: [20, 10]
      file: histogram_errors.png
    local_synchrony:
      feature1: pressure
      feature2: pressure
      window_size: 120
      figsize: [30, 6]
      file: local_synchony.png
    date_range:
      figsize: [20, 10]
      file: date_range.png
      metrics: [rms]
      dates:
        5-25to29-20:
          start: 2020/05/25 00:00
          end  : 2020/05/29 23:59
        8-25to30-20:
          start: 2020/08/25 00:00
          end  : 2020/08/30 23:59
        2-15to20-20:
          start: 2020/02/15 00:00
          end  : 2020/02/20 23:59
        11-15to20-20:
          start: 2020/11/15 00:00
          end  : 2020/11/20 23:59
        7-10to15-20:
          start: 2020/07/10 00:00
          end  : 2020/07/15 23:59
        8-04to07-20:
          start: 2020/08/04 00:00
          end  : 2020/08/07 23:59
        10-12to15-20:
          start: 2020/10/12 00:00
          end  : 2020/10/15 23:59
        12-25to27-20:
          start: 2020/12/25 00:00
          end  : 2020/12/27 23:59
  features:
    select:
    exclude:
